# fly.toml app configuration file generated for spreewise on 2023-11-21T12:44:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spreewise"
primary_region = "fra"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
